# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 683a9f02d97f56ec7fc09a0ea585fd6f496d92c0082d35d7524bacbab352cab630fe427c43bf0e3b742db86914862a14b1e7738e19674e0239c9a2c31f7693b5

test:
  secret_key_base: 692b70f5dc9b8876592a046074617aa7677ba181a739ef0a186e06a57e97c55d36907109f7ae9650efc97c1ef54b0236ac6ecd9d2cc82d7e78bc7082fece027b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
